{% set version = "0.5.1" %}
{% set python_min = "3.10" %}

package:
  name: fastplotlib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastplotlib/fastplotlib-{{ version }}.tar.gz
  sha256: 009ba1110f2ad1d94fe6ec4c63668e7dd3c18d9336185237a7bce725cfcbcbc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - numpy >=1.23.0
    - wgpu-py >=0.20.0
    - pygfx 0.12
    - cmap >=0.1.3

test:
  # Tests are in the run_test.py file
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fastplotlib/fastplotlib
  summary: A fast plotting library built using the pygfx render engine
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
