{% set version = "0.6.1" %}

package:
  name: fastplotlib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastplotlib/fastplotlib-{{ version }}.tar.gz
  sha256: 2de8b7cec83d5eeb7c39aacdf28994a46f87ce94354a684c8d3d89ebdbe796dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - numpy >=1.23.0
    - wgpu-py >=0.20.0
    - pygfx >=0.15
    - cmap >=0.1.3

test:
  # Tests are in the run_test.py file
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fastplotlib/fastplotlib
  summary: A fast plotting library built using the pygfx render engine
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
