{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: fastplotlib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastplotlib/fastplotlib-{{ version }}.tar.gz
  sha256: 42876e94fd8d9f2499d32e723cc975c6672a76f2876d9f3c4118cfa9998cd3f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23.0
    - wgpu-py >=0.18.1
    - pygfx ~=0.7.0
    - cmap

test:
  # Tests are in the run_test.py file
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fastplotlib/fastplotlib
  summary: A fast plotting library built using the pygfx render engine
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
